redhat-cne/cloud-event-proxy

- examples/manifests/producer.yaml
Producer.YAML was using consumer image, hence both were acting as consumers.
Fixed it to use producer image
> Fix producer image name

- Dockerfile
Building this image with [imagebuilder](https://github.com/openshift/imagebuilder)
results in the following error:
```
lstat /var/lib/docker/overlay2/.../merged/go/src/github.com/redhat-cne/cloud-event-proxy/go/src/github.com/redhat-cne/cloud-event-proxy/plugins/: no such file or directory
```
Most probably because `WORKDIR` is different than `/` in Brew/OSBS ... turning it into an absolute path fixes the problem.
> COPY plugins from absolute path to make imagebuilder happy

- Makefile
When building this image on a non-amd64 environment, we get the following errors:
```
go build  -o plugins/amqp_plugin.so -buildmode=plugin plugins/amqp/amqp_plugin.go
gcc_amd64.S: Assembler messages:
gcc_amd64.S:25: Error: unrecognized opcode: `pushq'
gcc_amd64.S:26: Error: unrecognized opcode: `pushq'
gcc_amd64.S:27: Error: unrecognized opcode: `pushq'
gcc_amd64.S:28: Error: unrecognized opcode: `pushq'
gcc_amd64.S:29: Error: unrecognized opcode: `pushq'
gcc_amd64.S:30: Error: unrecognized opcode: `pushq'
gcc_amd64.S:35: Error: unrecognized opcode: `call'
gcc_amd64.S:38: Error: unrecognized opcode: `popq'
gcc_amd64.S:39: Error: unrecognized opcode: `popq'
gcc_amd64.S:40: Error: unrecognized opcode: `popq'
gcc_amd64.S:41: Error: unrecognized opcode: `popq'
gcc_amd64.S:42: Error: …
```
> Let GOARCH be inferred from the environment

- Dockerfile
Reconciling with https://github.com/openshift/ocp-build-data/tree/645b06463cc0a4c847d252201a9da7d127bf85f5/images/cloud-event-proxy.yml
Co-authored-by: AOS Automation Release Team <noreply@redhat.com>
> Updating cloud-event-proxy images to be consistent with ART (#52)

- plugins/ptp_operator/metrics/metrics.go
with summary_interval=0 in ptp config, the ptp4l log will produce rms log without interface name , this was causing parsing error because parsing logic is based on position of the fields in the logs and expected to have interface name.
This PR takes care of both conditions with interface and without interface name in the ptp4l rms logs
> Bug 1999185: Fixed parse error when summary interval is set to 0

- examples/consumer/deployment/deployment.yaml
- plugins/ptp_operator/config/config.go
when user edits ptpconfig it triggers a file delete , and throws channel closed error.
This PR fixed close channel and pod crash
also converted consumer to daemonset
> Bug 2000253: fix pod crash

- cmd/main.go
- examples/consumer/deployment/deployment.yaml
- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/ptp_operator_plugin.go
ptp event threshold values  are set in ptpconfig and  they are read  in every  60 secs interval and update the threshold values mapped to interface name identified from ptp4l config file.
The bug was missing to identify interface names such as CLOCK_REALTIME, which is worker interface and was causing to miss new threshold values.
This PR also fixes a change to  load the threshold values  during the startup and then follow 60 secs interval  to watch and update. By fixing this change, it allows to fetch real values during startup and not relaying on default values till the 60 secs interval is met.
> Bug 2004137 : Fixed ptp threshold updates not updating values for CLOCK_REALTIME

- cmd/main.go
- examples/consumer/deployment/deployment.yaml
- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/ptp_operator_plugin.go
ptp event threshold values are set in ptpconfig and they are read in every 60 secs interval and update the threshold values mapped to interface name identified from ptp4l config file.
The bug was missing to identify interface names such as CLOCK_REALTIME, which is worker interface and was causing to miss new threshold values.
This PR also fixes a change to load the threshold values during the startup and then follow 60 secs interval to watch and update. By fixing this change, it allows to fetch real values during startup and not relaying on default values till the 60 secs interval is met.
> Bug 2004137: Fixed ptp threshold updates not updating values for CLOCK_REALTIME

- cmd/main.go
- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/stats/stats.go
This address Jira item: Report events for multiple masters per profile by its interface name [CNF-3111](https://issues.redhat.com/browse/CNF-3111)
1. Master offset is an offset of a slave interface from grandmaster, Since multiple slaves can be in a passive state and with a requirement that each PTP config will address single nic (Part of webhook validation to make sure this check is maintained).
2. The master offset is reported by masking the interface index 
3. example /cluster/cnfde7.ptp.lab.eng.bos.redhat.com/ptp/interface/**ens5fx**/master\
where slave interface ens5f1 master offset is reported as ens5fx, such that if you have multiple slave interface in passive role, the events and metrics are maintained its value  when passive-interface becomes active  slave
``` …
```
> Master event and metrics 

- Makefile
- go.mod
- go.sum
- pkg/common/common.go
- plugins/mock/mock_plugin.go
- plugins/ptp_operator/metrics/metrics.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event_data.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event_marshal.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event_reader.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event_unmarshal.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event_writer.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/resource.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/resource.go
- vendor/github.com/redhat-cne/sdk-go/v1/event/event.go
- vendor/modules.txt
Add `source` as a required attribute in event.
Update the `resource` under `event.data.values` to be resource
type instead of the source.
> Add source in event

- .github/workflows/main.yaml
CI Linting job fails intermittently due to timeout.
Increase the timeout to 3m. The timeout issue and suggested
solution can be found at
https://github.com/golangci/golangci-lint-action/issues/297
Also update the golangci-lint version to 1.42 since
golangci-lint starts to build docker image with go1.17 with
version 1.42.1.
> Add timeout to CI golangci-lint

- docs/development.md
- examples/consumer/main.go
- hack/common/cne.sh
- hack/common/common.sh
- hack/common/consumer.sh
- hack/deploy_test.sh
- plugins/mock/mock_plugin.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
- plugins/ptp_operator/socket/socket_test.go
- plugins/ptp_operator/types/types.go
Enable Flexible Registration for Multiple PTP Events
This adds the ability to subscribe to multiple events.
For each Publisher/Subscriber you create separate AMQ sender/listener objects
> CNF-4018 Enable Flexible Registration for Multiple PTP Events clock-class-change,status and os-sync

- examples/consumer/deployment/deployment.yaml
- plugins/ptp_operator/metrics/metrics.go
This PR depends on https://github.com/openshift/linuxptp-daemon/pull/76.
The PR generates event on PTP clock class change 
Linux PTP daemon will be sending log information on clock class change in the following format
`ptp4l[5196819.100]: [ptp4l.0.config] CLOCK_CLASS_CHANGE:248`
The event sidecar will parse the log and generate the event in the following format.
```
{
"id":"ebe86417-fe09-4ca0-93a0-4896cef6f5c7",
"type":"event.sync.ptp-status.ptp-clock-class-change",
"source":"/cluster/cnfde7.ptp.lab.eng.bos.redhat.com/ptp/unknown/master",
"dataContentType":"application/json",
"time":"2022-03-07T19:21:07.992550137Z",
"data":{
"version":"v1",
"values":[
{
"resource":"/sync/ptp-status/ptp-clock-class-change",
"dataType":"metric",
"valueType":"decimal64.3",
"value":"165"
}
]
}
}
```
The …
> clock class event

- .golangci.yaml
- cmd/main.go
- pkg/localmetrics/localmetrics.go
- pkg/plugins/handler.go
- pkg/restclient/client.go
- plugins/mock/mock_plugin.go
- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/config/config_test.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/ptp4lParse.go
- plugins/ptp_operator/metrics/registry.go
- plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
- plugins/ptp_operator/ptp4lconf/ptp4lConfig_test.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/socket/socket.go
- plugins/ptp_operator/socket/socket_test.go
- plugins/ptp_operator/stats/stats.go
- plugins/ptp_operator/types/types.go
- test/cne/cne.go
- test/utils/client/clients.go
- test/utils/namespaces/namespaces.go
- test/utils/nodes/nodes.go
linter was running without any options enabled.
The PR added .golanci.yaml file and fixed all linter complaints.
Refactored a few areas to fix lint issues
> Add go linter configuration file .golangci.yaml

- .github/workflows/main.yaml
Fixed golint failing due to go version 1.18 used by golinter
> Golinter failing due using go 1.18 instead of 17

- .github/workflows/main.yaml
Similar to: https://github.com/test-network-function/cnf-certification-test/pull/204 
https://github.com/actions/checkout/releases/tag/v3.0.2
`checkout` v3 is the latest available.
> Upgrade to v3 checkout action

- plugins/ptp_operator/metrics/ptp4lParse.go
The fix makes sure events are not triggered when master port goes to faulty state.
> Bug 2091599 :event is sent multiple times when non slave port goes to faulty.

- examples/manifests/kustomization.yaml
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/ptp4lParse.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/stats/stats.go
PR ads ability to call 3 events via CurrentState API
`
curl http://localhost:9085/api/cloudNotifications/v1/cluster/node/{node_name}/sync/ptp-status/ptp-clock-class-change/CurrentState
curl  http://localhost:9085/api/cloudNotifications/v1/cluster/node/{node_name}/sync/sync-status/os-clock-sync-state/CurrentState
curl  http://localhost:9085/api/cloudNotifications/v1/cluster/node/{node_name}/sync/ptp-status/lock-state/CurrentState
`
> Add Clock Class change event to CurrentState API call

- .github/workflows/main.yaml
- Dockerfile.local
- Makefile
- examples/consumer.Dockerfile.dev
- examples/producer/main.go
- go.mod
- go.sum
- hack/gofmt.sh
- pkg/restclient/client.go
- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
- plugins/ptp_operator/ptp4lconf/ptp4lConfig_test.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
ART update on image to use go.1.19 fails when running gofmt.
This PR fixes that issue
> upgrade to go1.19 and fix gofmt issue in 4.12

- plugins/ptp_operator/ptp_operator_plugin.go
get current-state was returning timeout for clock class .
This PR fixes that call
> Bug OCPBUGS-3296: PTP Event (AMQ) : Failed to get GetCurrentState for Events Clock Class Change

- go.mod
- go.sum
- vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
- vendor/modules.txt
Add retries when starting AMQP server to deal with the race condition when AMQP router starts later than cloud-event-proxy service, for example when a node is rebooted.
> Fix amq router race condition: update vendors only

- plugins/ptp_operator/metrics/logparser.go
removed error from log when parsing invalid no of fields 
> Bug OCPBUGS-4953: PTP events - error message on even log needs to be remove

- plugins/ptp_operator/metrics/ptp4lParse.go
> OCPBUGS-3667: Fix CLOCK_REALTIME going to HOLDOVER in metrics

- plugins/ptp_operator/metrics/manager.go
close channel , once closed stays in closed state and causing holdover time to cancel  immediately without changing state to FREERUN  
> BUG OCPBUGS-5377: Fix channel staying in close state

- cmd/main.go
- cmd/main_test.go
- go.sum
- pkg/plugins/handler.go
- pkg/plugins/handler_test.go
- plugins/amqp/amqp_plugin.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
- vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
Allow configurable timeout for initial amq connection.
Introduce amqp://nohup transportHost for local logging of events when amq connection is not available
> Amq connection configurable timeout and nohup

- cmd/main.go
- cmd/main_test.go
- go.mod
- go.sum
- pkg/plugins/handler.go
- pkg/plugins/handler_test.go
- plugins/amqp/amqp_plugin.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
- vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
- vendor/modules.txt
Allow configurable timeout for initial amq connection.
Introduce amqp://nohup transportHost for local logging of events when amq connection is not available
> [release-4.12] BUG OCPBUGS-5526: Amq connection configurable timeout and nohup

- .golangci.yaml
- cmd/main.go
- cmd/main_test.go
- go.mod
- go.sum
- pkg/plugins/handler.go
- pkg/plugins/handler_test.go
- plugins/amqp/amqp_plugin.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
- vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
- vendor/modules.txt
Allow configurable timeout for initial amq connection.
Introduce amqp://nohup transportHost for local logging of events when amq connection is not available
> [release-4.11] Bug OCPBUGS-4754: Amq connection configurable timeout and nohup

- cmd/main.go
- cmd/main_test.go
- go.mod
- go.sum
- pkg/plugins/handler.go
- pkg/plugins/handler_test.go
- plugins/amqp/amqp_plugin.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
- vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go
- vendor/modules.txt
Allow configurable timeout for initial amq connection.
Introduce amqp://nohup transportHost for local logging of events when amq connection is not available
> [release-4.10] Bug OCPBUGS-4755: Amq connection configurable timeout and nohup

- cmd/main.go
- pkg/common/common.go
Add multi node support for HTTP .
This needs to be back ported to 4.12
> Add multi node support for http

- cmd/main.go
- examples/manifests/consumer.yaml
- pkg/common/common.go
when deploying consumer app, if NODE_NAME is used as placeholder for publisher URL , the sidecar was skipping replacement and this was resulting from identifying valid .publisher service endpoint.
> BUG OCPBUGS-7826: Add multi node support for consumer to identify publishers

- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/registry.go
- plugins/ptp_operator/ptp_operator_plugin.go
This fixes retaining ptp process metrics when ptpconfig is deleted
OCPBUGS-7811 WPC GM - a new process file is created when applying a deleted gm ptpconfig
> OCPBUGS-7811: remove ptp process metrics when ptpcfig is  deleted

- plugins/ptp_operator/ptp_operator_plugin.go
fixes bug ts2phc state is LOCKED after the gm ptpconfig is deleted
> OCPBUGS-7808: Remove ptp metrics for masterclock on delete of ptpconfig

- Makefile
- cmd/main.go
- go.mod
- go.sum
- pkg/common/common.go
- plugins/README.md
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/ptp4lParse.go
- plugins/ptp_operator/metrics/registry.go
- plugins/ptp_operator/types/types.go
- vendor/github.com/redhat-cne/sdk-go/pkg/channel/doc.go
- vendor/github.com/redhat-cne/sdk-go/pkg/channel/pipeline.go
- vendor/github.com/redhat-cne/sdk-go/pkg/channel/types.go
- vendor/github.com/redhat-cne/sdk-go/pkg/errorhandler/doc.go
- vendor/github.com/redhat-cne/sdk-go/pkg/errorhandler/errorhandler.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event_data.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/event_writer.go
- vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go
- vendor/github.com/redhat-cne/sdk-go/pkg/protocol/doc.go
- vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
- vendor/github.com/redhat-cne/sdk-go/pkg/protocol/interface.go
- vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
- vendor/github.com/redhat-cne/sdk-go/pkg/types/value.go
- vendor/github.com/redhat-cne/sdk-go/pkg/util/wait/wait.go
- vendor/github.com/redhat-cne/sdk-go/v1/http/http.go
- vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
- vendor/modules.txt
> [release-4.12] OCPBUGS-7561: Fix SLAVE port going to master or listening state

- plugins/ptp_operator/metrics/ptp4lParse.go
- plugins/ptp_operator/metrics/registry.go
> OCPBUGS-7974: PTP BC: an unnecessary openshift_ptp_clock_state metric is shown

- examples/simplehttp/common/httpclient.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/ptp4lParse.go
Fix CLOCK_REALTIME not updated in metrics with ts2phc enabled
> OCPBUGS-8714: With GM config, phc2sys clock lock state is shown as FREERUN in ptp metrics while it should be LOCKED

- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/metrics/metrics.go
…metrics show slaves as FREERUN
> OCPBUGS-11233: PTP - When GM and downstream slaves are configured on same server, ptp metrics show slaves as FREERUN

- cmd/main.go
- examples/consumer/main.go
- pkg/common/common.go
fixed node name requirement for HTTP
> OCPBUGS-8249: Backport HTTP support fixes to 4.12 with nodename replaced

- examples/consumer/main.go
Logs don't need newlines.
Currently, the logs looks like this:
```
time="2023-04-25T16:08:18Z" level=info msg="Latency for the event: 324 ms\n"
```
> Remove \n from logs in consumer example

- .github/workflows/main.yaml
- go.mod
go builder in Dockerfile is 1.20. This commit
makes go directive in go.mod consistent with the change.
> OCPBUGS-14991: bump go version to 1.20

- Makefile
This commit solves a situation when the sidecar  fails to load plugins with an error: "plugin was built with a different version of package ...".  It appears that some build artifacts were stored in docker cache and reused in future builds, causing this incompatibility. The `--no-cache` flag added to the `docker build` command is fixing the issue.
/cc @aneeshkp @nishant-parekh @jzding
> OCPBUGS-14991: Always fully build plugins with the main program

- plugins/ptp_operator/event/event.go
> OCPBUGS-17322: linuxptp-daemon pod status changes to Error and CrashLoopBackOff after a ptpconfig is loaded

- plugins/ptp_operator/event/event.go
- plugins/ptp_operator/event/event_test.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/metrics_test.go
- plugins/ptp_operator/metrics/registry.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/stats/stats.go
- plugins/ptp_operator/stats/stats_test.go
> OCPBUGS-25547: PTP metrics still includes metrics for old config after deleting a ptpconfig 

- plugins/ptp_operator/ptp_operator_plugin.go
fix metrics clean up on delete of ptp config
> [release-4.13] Bug OCPBUGS-26508: PTP metrics still includes metrics for old config after deleting a ptpconfig 

- Makefile
- plugins/ptp_operator/_testprofile/ptpha
- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/config/config_test.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/registry.go
- plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/stats/stats.go
HELP openshift_ptp_ha_profile_status 0 = INACTIVE 1 = ACTIVE 0 #  TYPE openshift_ptp_ha_profile_status gauge openshift_ptp_ha_profile_status{node="node1",process="phc2sys",profile="profile1"} 1 openshift_ptp_ha_profile_status{node="node1",process="phc2sys",profile="profile2"} 0
known issue 
1. threshold  metrics are not getting cleared when ptp ha are deleted
> Add ptp ha metrics

- plugins/ptp_operator/ptp_operator_plugin.go
PR to fix file-watcher update introduced default for select that in turn introduced  cpu spike.
https://github.com/redhat-cne/cloud-event-proxy/pull/296
This PR fixes CPU spike by removing default from channel selector and introduce new channel to process config map after file delete operation is performed
> fix cpu spike due to default in select

- examples/consumer.Dockerfile
- examples/consumer/main.go
- examples/manifests/consumer.yaml
- pkg/common/common.go
Previously, the consumer could only receive events if the producer was already running when the consumer started. This created a dependency issue, where a consumer restart was necessary if the producer was restarted or enabled after the consumer was already running.
This PR addresses this limitation by introducing a publisher health check. The consumer now performs a health check on the producer every second. This check ensures that the producer is healthy before subscribing to its events. This eliminates the need for consumer restarts due to producer restarts or enablement after consumer startup.
Benefits:
Improved Consumer Resilience: This change enhances the consumer's robustness by making it independent of the producer's initial state.
Simplified Management: No more consumer restarts …
> Enhance Consumer Application with Periodic Publisher Health Check

- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/config/config_test.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/registry.go
- plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/stats/stats.go
This is a backport of https://github.com/redhat-cne/cloud-event-proxy/pull/294 and https://github.com/redhat-cne/cloud-event-proxy/pull/296 except HA related changes.
> [release-4.15] OCPBUGS-32305: fix missing openshift_ptp_process_status metric after initial installation

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/stats/stats.go
update GNSS sync state to send enum value as per O-Ran
The value of GPS  sync State will be 
1. SYNCHRONIZED --> gpsFix >=3
2.  ACQUIRING_SYNC  --> gpsFix=1-2  or OFFSET is not in range or GPSFIX is in sync 
3. ANTENNA_DISCONNECTED --> gpsfix ==0 
4.  FREERUN  --> This is when event not found or error 
Example of cold boot 'Status | Offset  | gpsfix | `
```
| 2024-05-30T21:17:24Z | ANTENNA-DISCONNECTED | 2.0000146e+07 | 0 | event.sync.gnss-status.gnss-state-change    | /cluster/node/cnfdg3.ptp.eng.rdu2.dc.redhat.com/ens4fx/master/gpsFix
| 2024-05-30T21:17:30Z | SYNCHRONIZED | 24 | 3 | event.sync.gnss-status.gnss-state-change       | /cluster/node/cnfdg3.ptp.eng.rdu2.dc.redhat.com/ens4fx/master/gpsFix  
```						
```
{
"id": "4fceb3e1-ea86-4024-beb8-2c39dc6ac641",
"type": …
```
> OCPBUGS-31575: GNSS EVENT state is not following O-Ran spec defined values

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/stats/stats.go
update GNSS sync state to send enum value as per O-Ran
The value of GPS sync State will be
SYNCHRONIZED --> gpsFix >=3
ACQUIRING_SYNC --> gpsFix=1-2 or OFFSET is not in range or GPSFIX is in sync
ANTENNA_DISCONNECTED --> gpsfix ==0
FREERUN --> This is when event not found or error
Example of cold boot 'Status | Offset | gpsfix | `
| 2024-05-30T21:17:24Z | ANTENNA-DISCONNECTED | 2.0000146e+07 | 0 | event.sync.gnss-status.gnss-state-change    | /cluster/node/cnfdg3.ptp.eng.rdu2.dc.redhat.com/ens4fx/master/gpsFix
| 2024-05-30T21:17:30Z | SYNCHRONIZED | 24 | 3 | event.sync.gnss-status.gnss-state-change       | /cluster/node/cnfdg3.ptp.eng.rdu2.dc.redhat.com/ens4fx/master/gpsFix  
{
"id": "4fceb3e1-ea86-4024-beb8-2c39dc6ac641",
"type": "event.sync.gnss-status.gnss-state-change",
"source": …
> [release-4.15] OCPBUGS-35888: GNSS EVENT state is not following O-Ran spec defined values

- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/config/config_test.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/stats/stats.go
update GNSS sync state to send enum value as per O-Ran
The value of GPS sync State will be
SYNCHRONIZED --> gpsFix >=3
ACQUIRING_SYNC --> gpsFix=1-2 or OFFSET is not in range or GPSFIX is in sync
ANTENNA_DISCONNECTED --> gpsfix ==0
FREERUN --> This is when event not found or error
Example of cold boot 'Status | Offset | gpsfix | `
| 2024-05-30T21:17:24Z | ANTENNA-DISCONNECTED | 2.0000146e+07 | 0 | event.sync.gnss-status.gnss-state-change    | /cluster/node/cnfdg3.ptp.eng.rdu2.dc.redhat.com/ens4fx/master/gpsFix
| 2024-05-30T21:17:30Z | SYNCHRONIZED | 24 | 3 | event.sync.gnss-status.gnss-state-change       | /cluster/node/cnfdg3.ptp.eng.rdu2.dc.redhat.com/ens4fx/master/gpsFix  
{
"id": "4fceb3e1-ea86-4024-beb8-2c39dc6ac641",
"type": "event.sync.gnss-status.gnss-state-change",
"source": …
> [release-4.14] OCPBUGS-35889:  GNSS EVENT state is not following O-Ran spec defined values

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/stats/stats.go
ts2phc process termination only triggers FREERUN and doesn't recover back .
This PR fixes this issue by reading process down status and handle ts2phc event
> OCPBUGS-35587: T-GM - ts2phc process restart doesn't update PTP syncState when the process recovered

- .golangci.yaml
- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/event/event.go
- plugins/ptp_operator/metrics/logData.go
- plugins/ptp_operator/metrics/logData_test.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/registry.go
- plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
- plugins/ptp_operator/stats/stats.go
This PR enabled metrics and events for syncE
Metrics available 
` openshift_ptp_clock_state{iface="ens7f0",node="cnfdg33.ptp.eng.rdu2.dc.redhat.com",process="synce4l"} 1
openshift_ptp_clock_state{iface="ens7f1",node="cnfdg33.ptp.eng.rdu2.dc.redhat.com",process="synce4l"} 1
openshift_ptp_process_restart_count{config="synce4l.0.config",node="cnfdg33.ptp.eng.rdu2.dc.redhat.com",process="synce4l"} 1
openshift_ptp_process_status{config="synce4l.0.config",node="cnfdg33.ptp.eng.rdu2.dc.redhat.com",process="synce4l"} 0
HELP openshift_ptp_synce_clock_quality network_option1: ePRTC = 32 PRTC = 34 PRC =257  SSU-A = 259 SSU-B = 263 EEC1 = 266 network_option2: ePRTC = 34 PRTC = 33 PRS =256 STU = 255 ST2 = 262 TNC = 259 ST3E =268 EEC2 =265 PROV =269
TYPE openshift_ptp_synce_clock_quality gauge …
> Enable synce metrics and events 

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/ptp_operator_plugin.go
Synce Clock Quality event 
```
{
"id": "13cde259-d48f-40db-aaf7-eeea07cfae14",
"type": "event.sync.synce-status.synce-clock-quality-change",
"source": "/cluster/node/cnfdg33.ptp.eng.rdu2.dc.redhat.com/sync/synce-status/clock-quality",
"dataContentType": "application/json",
"time": "2024-08-05T18:47:36.381119534Z",
"data": {
"version": "1.0",
"values": [
{
"ResourceAddress": "/cluster/node/cnfdg33.ptp.eng.rdu2.dc.redhat.com/synce1/ens7f0/Ql",
"data_type": "metric",
"value_type": "decimal64.3",
"value": "1"
},
{
"ResourceAddress": "/cluster/node/cnfdg33.ptp.eng.rdu2.dc.redhat.com/synce1/ens7f0/extQl",
"data_type": "metric",
"value_type": "decimal64.3",
"value": "32"
}
]
}
}
```
Synce State
```
{
"id": "4f20e0e4-15b3-4724-b39e-2f9006d664ad",
"type": …
```
> Fix synce events for getCurrentState and regular event

- cmd/main.go
- go.mod
- go.sum
- pkg/restclient/client.go
- pkg/storage/kubernetes/client.go
- vendor/github.com/redhat-cne/rest-api/v2/routes.go
- vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
- vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
- vendor/modules.txt
Fixe both v1 and v2 cleanup: reset fail count when a event is successfully delivered.
Also added API support for deleting all subscriptions:
DELETE /api/ocloudNotifications/v2/subscriptions
> OCPBUGS-35799: OCPBUGS-38284: clean up subscriptions when lost connection to consumer

- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/manager_test.go
- plugins/ptp_operator/metrics/metrics_test.go
- plugins/ptp_operator/metrics/ptp4lParse.go
This PR introduces a change to the Boundary Clock (BC) and Ordinary Clock (OC) behavior, ensuring that the system remains in the HOLDOVER state when a previously faulty interface becomes operational again. The holdover state will persist until the PTP synchronization state is detected as LOCKED or until the holdover duration times out.
Key Changes:
Added logic to maintain the HOLDOVER state after a faulty interface recovers, preventing premature exit from holdover.
HOLDOVER will remain active until either:
-          The PTP sync state transitions to LOCKED.
-         The holdover timer reaches its limit and times out.
Ensured this behavior applies to both BC and OC configurations.
Purpose:
This change helps to maintain clock stability by ensuring that the system does not exit the …
> OCPBUGS-41636: Maintain HOLDOVER for BC/OC when faulty interface returns until Clock is locked

- examples/consumer/main.go
- pkg/common/common.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
Implement /sync/sync-status/sync-state.
Trigger overall sync-state event when either ptp-state-change or os-clock-sync-state-change events are triggered.
> [release-4.14] OCPBUGS-41353: implement over all sync-status

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/metrics.go
This PR  handles T-GN holdover fixes introduced in https://github.com/openshift/linuxptp-daemon/pull/367
New metrics getting generated for ts2phc  in holdover state
> OCPBUGS-19838:PTP HW Clock Class after disabling NMEA sentences - Handle T-GM holdover

- cmd/main.go
- pkg/storage/kubernetes/client.go
- pkg/storage/kubernetes/client_test.go
Tests done:
1. deploy ptp-operator, update ptpoperatorconfig to enable v1 event
2. deploy v1 consumer => verify configmap and events
3. update update ptpoperatorconfig to enable v2 event => verify configmap cleaned up
4. undeploy v1 consumer and deploy v2 consumer => verify configmap and events
5. reboot linuxptp-daemon pod => verify configmap and events
6. reboot consumer => verify configmap and events
7. reboot linuxptp-daemon pod again => verify configmap and events
8. update ptpoperatorconfig to enable v1 event => verify configmap cleaned up
9. undeploy v2 consumer and deploy v1 consumer => verify configmap and events
10. reboot linuxptp-daemon pod => verify configmap and events
> OCPBUGS-42840: cleanup configmap when event apiVersion change

- examples/consumer/main.go
This PR removes the hardcoded replacement of apiAddr in the consumer application when switching from V1 to V2. Instead of relying on manual hardcoding, the application will now dynamically use the first publisher from the provided list via the --http-event-publishers argument.
The new implementation will fetch the first publisher from the following format :
--http-event-publishers=ptp-event-publisher-service-NODE_NAME.openshift-ptp.svc.cluster.local:9043
> Remove hard coded replacement of api addr in consumer deployment 

- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/manager_test.go
- plugins/ptp_operator/metrics/ptp4lParse.go
This PR addresses two issues:
1.  Fix Holdover Event Triggering for T-GM :
Issue: When the T-GM (Telecom Grandmaster) entered holdover mode, the associated events were not generated, although metrics were successfully created.
Resolution: This PR ensures that event generation is correctly triggered for the holdover state, aligning events with the metrics generated.
2. Eliminate Duplicate Clock Class Events:
Issue: Multiple events were being generated for the same clock class value, causing redundancy.
Resolution: Duplicate events for the same clock class value have been removed, streamlining event reporting and reducing noise.
> OCPBUGS-44208: Fix Holdover Event Triggering for T-GM and Minimize Redundant Clock Class Events:

- examples/consumer/main.go
- go.mod
- go.sum
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/resource.go
- vendor/modules.txt
Fix Backward Compatibility for PTP Clock-Class Event Subscription 
The problem arises because the V1 version of PTP events subscribed to the resource address /sync/ptp-status/ptp-clock-class-change, which was updated to /sync/ptp-status/clock-class in V2 as per O-RAN spec.
As a result, older versions referencing /sync/ptp-status/ptp-clock-class-change failed to subscribe to clock-class events.
This PR resolves the issue by introducing a new enum type, PtpClockClassV1, which refers to the older event resource.
The solution ensures backward compatibility for V1 while adhering to the O-RAN 7.2.3.10 specification for the PtpClockClass notification.
Key Changes:
In Cloud-event-proxy ,  manages different clock type subscription names by detecting API version 
if v1Api {
+ …
> OCPBUGS-44954: PTP operator Event Notification API breaking change within 4.16 release

- examples/consumer/main.go
- go.mod
- go.sum
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
- vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/resource.go
- vendor/modules.txt
Fix Backward Compatibility for PTP Clock-Class Event Subscription
The problem arises because the V1 version of PTP events subscribed to the resource address /sync/ptp-status/ptp-clock-class-change, which was updated to /sync/ptp-status/clock-class in V2 as per O-RAN spec.
As a result, older versions referencing /sync/ptp-status/ptp-clock-class-change failed to subscribe to clock-class events.
This PR resolves the issue by introducing a new enum type, PtpClockClassV1, which refers to the older event resource.
The solution ensures backward compatibility for V1 while adhering to the O-RAN 7.2.3.10 specification for the PtpClockClass notification.
Key Changes:
In Cloud-event-proxy , manages different clock type subscription names by detecting API version
```
if v1Api { …
```
> [release-4.16] OCPBUGS-44900: PTP operator Event Notification API breaking change within 4.16 release

- go.mod
- go.sum
- vendor/github.com/redhat-cne/rest-api/.gitignore
- vendor/github.com/redhat-cne/rest-api/v2/routes.go
- vendor/github.com/redhat-cne/rest-api/v2/server.go
- vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
- vendor/modules.txt
Current code checking for existing subscription by  resourceAddress only. This fix added checking for EndpointURI so that multiple clients (with different EndpointURIs) can create subscriptions for the same resourceAddress.
> OCPBUGS-46150: fix subscription for multiple clients

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
This is a cherrypick from #379
> OCPBUGS-45866 : Fix GM State Transition Event Generation

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
This is a cherrypick from #379
> OCPBUGS-47515: [release-4.17] Fix GM State Transition Event Generation

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
This is a cherrypick from #379
> OCPBUGS-47518: [release-4.16] Fix GM State Transition Event Generation

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
This is a cherrypick from #379
> OCPBUGS-47519: [release-4.15] Fix GM State Transition Event Generation

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/metrics_test.go
Fixes backport mistake that caused ptpStateChange event never to be sent
> OCPBUGS-47709: [release-4.17] fix backport mistake

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/metrics_test.go
This is a manual cherrypick from #384 and #397
> OCPBUGS-45308: Fix gm states 4.14

- go.mod
- go.sum
- vendor/github.com/redhat-cne/rest-api/.gitignore
- vendor/github.com/redhat-cne/rest-api/v2/routes.go
- vendor/github.com/redhat-cne/rest-api/v2/server.go
- vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_unmarshal.go
- vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
- vendor/modules.txt
Update sdk-go and rest-api modules to fix the following issues:
[OCPBUGS-47791](https://issues.redhat.com/browse/OCPBUGS-47791)
Unable to subscribe two or more consumers to the same PTP event
[OCPBUGS-47792](https://issues.redhat.com/browse/OCPBUGS-47792)
Bad HTTP response (409) sent when the subscription request is not correct
> [release-4.17] OCPBUGS-47791: OCPBUGS-47792: update sdk-go and rest-api

- go.mod
- go.sum
- vendor/github.com/redhat-cne/rest-api/.gitignore
- vendor/github.com/redhat-cne/rest-api/v2/routes.go
- vendor/github.com/redhat-cne/rest-api/v2/server.go
- vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_unmarshal.go
- vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
- vendor/modules.txt
Update sdk-go and rest-api modules to fix the following issues:
[OCPBUGS-47795](https://issues.redhat.com/browse/OCPBUGS-47795)
Unable to subscribe two or more consumers to the same PTP event
[OCPBUGS-47793](https://issues.redhat.com/browse/OCPBUGS-47793)
Bad HTTP response (409) sent when the subscription request is not correct
> [release-4.16] OCPBUGS-47795: OCPBUGS-47793: update sdk-go and rest-api

- .github/workflows/build.yaml
Replace quay.io Build Trigger with Github workflow.
Trigger the build and push of consumer image when a PR is merged to `main` or `release-4.18` branches.
For PR merged to main branch, this workflow will create the following images:
- quay.io/redhat-cne/cloud-event-consumer:latest (multi-arch)
- quay.io/redhat-cne/cloud-event-consumer:latest-arm64
- quay.io/redhat-cne/cloud-event-consumer:latest-amd64
For PR merged to release-4.18 branch, this workflow will create the following images:
- quay.io/redhat-cne/cloud-event-consumer:release-4.18 (multi-arch)
- quay.io/redhat-cne/cloud-event-consumer:release-4.18-arm64
- quay.io/redhat-cne/cloud-event-consumer:release-4.18-amd64
> enable multi-arch consumer image

- .github/workflows/build.yaml
- Makefile
Upon agreement with QE, update consumer image label for release-4.18 from `release-4.18` to `4.18` to be consistent with other images.
Also simplified the make commands for dev testing with macOs.
> CNF-17240: Change consumer image label release-4.18 to 4.18

- go.mod
- go.sum
- vendor/github.com/redhat-cne/rest-api/v2/server.go
- vendor/modules.txt
Update go.mod to use rest-api v1.23.1, which includes a fix for a race condition when reading the server status.
api fix: [redhat-cne/rest-api#90](https://github.com/redhat-cne/rest-api/pull/90)
> OCPBUGS-54543: Data race in Server.status access causes instability in cloud-event-proxy

- .github/workflows/main.yaml
[The Ubuntu 20.04 Actions runner image will begin deprecation](https://github.com/actions/runner-images/issues/11101).
> Update Github action runners

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/manager_test.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/ptp4lParse.go
- plugins/ptp_operator/ptp_operator_plugin.go
Observed Behavior:
CLOCK_REALTIME continued to report as LOCKED even when both active and inactive slave interfaces were down.
Fix: 
Added logic to evaluate HA profile state consistency
CLOCK_REALTIME is now transitioned to FREERUN only if all HA profiles are in FAULTY state
Ensures LOCKED is not reported falsely when no valid upstream source is active
> OCPBUGS-53247: CLOCK_REALTIME state reports 1 (locked) when both active and inactive interfaces are down in BC/OC HA environment

- Makefile
- cmd/main.go
- examples/consumer/main.go
- pkg/restclient/client.go
- pkg/storage/kubernetes/client.go
- pkg/storage/kubernetes/client_test.go
consumer changes:
- re-subscribe in case of non-recoverable error at server side, for example lost of persist data in configmap
- add git commit ID in consumer image
sidecar changes:
- add retry in configMap creation
- add trace and error handling to configMap creation and updating
> OCPBUGS-45680: add error handling in configmap and consumer app subscription

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/ptp4lParse.go
Handling for TBC logs in an expected format, which should be added to
the linuxptp-daemon soon.
T-BC[1743005894]:[ptp4l.0.config] ens7f0  offset  55 T-BC-STATUS s0
> parse BC holdover

- go.mod
- go.sum
- pkg/common/common.go
- vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
- vendor/modules.txt
Reduce logs in consumer sidecar from 3 to 1 for each v1 event pull. See detail in https://issues.redhat.com/browse/OCPBUGS-55264
> OCPBUGS-55391: reduce event logs

- Makefile
- cmd/main.go
- examples/consumer/main.go
- examples/manifests/consumer.yaml
- pkg/common/common.go
- pkg/restclient/client.go
- pkg/storage/kubernetes/client.go
- pkg/storage/kubernetes/client_test.go
Part of changes are cherry-picks of https://github.com/redhat-cne/cloud-event-proxy/pull/444, https://github.com/redhat-cne/cloud-event-proxy/pull/469 and https://github.com/redhat-cne/cloud-event-proxy/pull/472
consumer changes:
re-subscribe in case of non-recoverable error at server side, for example lost of persist data in configmap
add git commit ID in consumer image
* New change: In v1, eventpullErrorCount is used to recover subscriptions from this scenario.
sidecar changes:
add retry in configMap creation
add trace and error handling to configMap creation and updating
> [release-4.18] OCPBUGS-55121: add error handling in configmap and consumer app subscription

- test/cne/cne.go
consumer pull events at 60 seconds interval. Add 60 seconds delay when capture logs to make sure event pull is captured.
> fix e2e-aws intermittent failure

- examples/consumer/main.go
- plugins/ptp_operator/metrics/logparser.go
This pull request addresses an issue where unnecessary error messages were being logged when retrieving the DPLL (Digital Phase-Locked Loop) phase offset in PTP statistics. 
The error log was misleading because it did not account for the time required for the DPLL to acquire phase details. This caused noise flooding , especially during the initial setup or reconfiguration.
Problem:
The existing implementation logged an error whenever the DPLL phase offset could not be immediately retrieved.
Solution:
Removed the error logging for the phase offset retrieval in the GetDependsOnValueState function.
noise: error parsing phase offset value not found dpll
>  OCPBUGS-56053: Suppress Error Logging for DPLL Phase Offset Calculation

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/manager_test.go
- plugins/ptp_operator/metrics/metrics_test.go
- plugins/ptp_operator/metrics/ptp4lParse.go
- plugins/ptp_operator/ptp_operator_plugin.go
- plugins/ptp_operator/ptp_operator_plugin_test.go
- plugins/ptp_operator/types/types.go
manual cherry pick of  https://github.com/redhat-cne/cloud-event-proxy/pull/486
This PR introduces two key improvements in the getCurrentStatOverrideFn logic used to determine and report PTP synchronization state.
Consistent Node Sync State Evaluation
The node-level synchronization state is now determined based on a consistent and comprehensive evaluation of:
PHC lock state(master)
OS clock (CLOCK_REALTIME) state
For T-GM nodes, additional dependencies:
DPLL state
GNSS signal state
Frequency traceability, etc.
This ensures that the overall sync state accurately reflects the health and synchronization status of all relevant components on the node.
2. Structured and Hierarchical ResourceAddress in CloudEvents
To improve clarity and traceability, the ResourceAddress field in the event data …
> [release-4.18] OCPBUGS-56272: ptp all sync-state event should be FREERUN. Instead sends event as LOCKED and resource address should be consistent

- .golangci.yaml
- cmd/main_test.go
- pkg/plugins/handler_test.go
- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/config/config_test.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/manager_test.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/ptp4lParse.go
- plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
- plugins/ptp_operator/ptp_operator_plugin.go
This pull request introduces support for “T-BC” (time-based clock) events emitted by the linuxptp daemon, while disabling the generation of redundant ptp4l-based trigger events within the cloud-event-proxy. For T-BC , the proxy will:
Parse and emit only unassisted T-BC events received from the linuxptp daemon in the following format:
```
LOCKED
T-BC[1743005894]:[ptp4l.0.config] ens7f0  offset  123 T-BC-STATUS s2
FREERUN
T-BC[1743005894]:[ptp4l.0.config] ens7f0  offset  123 T-BC-STATUS s0/s1
HOLDOVER
T-BC[1743005894]:[ptp4l.0.config] ens7f0  offset  123 T-BC-STATUS s3 holdover
```
When T-BC profiel detected, disable any event‐generation logic based on ptp4l’s internal state transitions (e.g. lock/unlock triggers) inside the proxy itself. 
Instead, ptp4l will only be used for port‐state …
> Enable Unassisted T-BC Event Handling and Disable Internal ptp4l Triggers in cloud-event-proxy

- go.mod
- go.sum
- plugins/ptp_operator/ptp_operator_plugin.go
- vendor/github.com/redhat-cne/rest-api/v2/routes.go
- vendor/modules.txt
Previously, getCurrentState returned a FREERUN state with placeholder ResourceAddresses ("event-not-found" or "ptp-not-set") when event data was unavailable, for example when the event socket wasn't ready, risking cell site outages. This update ensures a 404 Not Found status is returned instead, accurately signaling the absence of valid event data.
Add validation to prevent Stats.ClockClass() from returning an uninitialized value (0), which could result in unintended events with clockClass=0.
> OCPBUGS-59969: Handle missing event data in getCurrentState with 404 response

- .golangci.yaml
- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/ptp_operator_plugin.go
assisted by : Cursor AI
Problem
When the PTP container restarts, it fails to properly pick up config information and complete metrics for interface roles. This results in:
Interface roles remain UNKNOWN: The validLogToProcess function fails validation because interfaces have incomplete role assignments
Missing interface_role metrics: Metrics are not generated for interface roles during config processing
Log processing skipped: The system skips processing PTP logs due to validation failures, preventing proper metrics collection.
KNOWN ISSUE: ```
The interface role will be based on ptp config , if anything changed , side car won't know.
Future fix to update interface role from the daemon will fix this problem
> OCPBUGS-60261: Fix PTP interface role assignment and metrics generation on container restart [release-4.19]

- go.mod
- go.sum
- plugins/ptp_operator/ptp_operator_plugin.go
- vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go
- vendor/modules.txt
Previously, getCurrentState returned a FREERUN state with placeholder ResourceAddresses ("event-not-found" or "ptp-not-set") when event data was unavailable, for example when the event socket wasn't ready, risking cell site outages. This update ensures a 400 status is returned instead, accurately signaling the absence of valid event data.
Add validation to prevent Stats.ClockClass() from returning an uninitialized value (0), which could result in unintended events with clockClass=0.
> [release-4.15] OCPBUGS-60622: Handle missing event data in getCurrentState with 400 response

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/ptp_operator_plugin.go
This commit fixes a bug in ts2phc state metric in the T-BC use case. The ts2phc metric for the upstream interface was missing after the pod start, or stuck on 0 after a configuration change and daemon restart. This was caused by the fact that ts2phc in the T-BC use case does not log clock updates when ptp4l updates the same clock. The solution is to impose the leading PHC state (derived from the overall T-BC state) onto the ts2phc metric for the same PHC
/cc @aneeshkp @jzding @nocturnalastro @josephdrichard
> OCPBUGS-61703 : Fix T-BC ts2phc upstream interface metric

- plugins/ptp_operator/metrics/filesystem.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/manager.go
- plugins/ptp_operator/metrics/manager_test.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/metrics_test.go
- plugins/ptp_operator/metrics/ptp4lParse.go
- plugins/ptp_operator/ptp_operator_plugin.go
Saves data to file so it survives a crash
Then triggers logs to see if state changed during crash to starting back up.
Depends on: https://github.com/k8snetworkplumbingwg/linuxptp-daemon/pull/80
> Save and load basic metrics to file in store and trigger logs from linuxptp-daemon

- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
A log with the word offset and enough feilds was being parsed as a metrics when it should have been skipped
> OCPBUGS-60613: Skip line if type convertions error in extractRegularMetrics

- plugins/ptp_operator/config/config.go
- plugins/ptp_operator/metrics/logparser.go
- plugins/ptp_operator/metrics/logparser_test.go
- plugins/ptp_operator/metrics/metrics.go
- plugins/ptp_operator/metrics/metrics_test.go
- plugins/ptp_operator/ptp4lconf/ptp4lConfig.go
- plugins/ptp_operator/ptp_operator_plugin.go
Add support for setting OS clock sync state based on information from chronyd.  More specifically, when chronyd is controlling the OS clock, then the OS clock sync state should be reported as locked.
> basic support for chronyd
