redhat-cne/cloud-event-proxy

README.md
=> Added go report,go-doc and License to readme

cmd/main_test.go, plugins/ptp_operator/ptp_operator_plugin.go, plugins/ptp_operator/ptp_operator_plugin_test.go
=> Fixed testcase

.gitignore, Makefile
=> git ignore

README.md, cmd/main.go, docs/metrics.md, examples/consumer/main.go, examples/producer/main.go, go.mod, go.sum, pkg/common/common.go, pkg/localmetrics/localmetrics.go, pkg/plugins/handler.go, pkg/plugins/handler_test.go, pkg/restclient/client.go, plugins/amqp/amqp_plugin.go, plugins/ptp_operator/ptp_operator_plugin.go, plugins/ptp_operator/ptp_operator_plugin_test.go
=> Add metrics docs and copyright header

docs/metrics.md
=> Fix metrics docs

docs/metrics.md
=> metrics docs

examples/manifests/consumer.yaml, examples/manifests/producer.yaml
=> Add namespace to deployment

examples/manifests/service.yaml
Added namespace to service,otherwise it would get created under default
=> Added namespace to service

docs/development.md
=> Update examples cluster deployment procedure

cmd/main.go, cmd/main_test.go, go.mod, go.sum, pkg/common/common.go, pkg/plugins/handler_test.go, plugins/ptp_operator/ptp_operator_plugin_test.go
This PR updates sidecar to use wait method implemented in SDK and also changes close channel type to empty struct
=> Implementing wait method

.github/workflows/main.yaml, cmd/main.go, plugins/hw_event/hw_event_plugin.go
=> fix linting issues

examples/consumer/main.go, go.mod, go.sum, pkg/plugins/handler.go, plugins/hw_event/hw_event_plugin.go, plugins/ptp_operator/ptp_operator_plugin.go, plugins/ptp_operator/socket/socket_test.go
=> update based on sdk-go hardware-event changes

Dockerfile.local, Makefile, cmd/main.go, cmd/main_test.go, docs/metrics.md, examples/consumer.Dockerfile.local, examples/consumer/deployment/deployment.yaml, examples/consumer/deployment/namespace.yaml, examples/consumer/deployment/roles.yaml, examples/consumer/deployment/sa.yaml, examples/consumer/deployment/service.yaml, examples/consumer/main.go, examples/manifests/configmap.yaml, examples/producer.Dockerfile, examples/producer/main.go, go.mod, go.sum, hack/build-image.sh, hack/local-ldd-dep.sh, pkg/common/common.go, pkg/localmetrics/localmetrics.go, pkg/plugins/handler.go, pkg/plugins/handler_test.go, pkg/restclient/client.go, plugins/amqp/amqp_plugin.go, plugins/mock/mock_plugin.go, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/ptp_operator_plugin.go, plugins/ptp_operator/ptp_operator_plugin_test.go
Added mock plugin and fixed metrics
Added local docker file to build local with local deps
=> Add metrics to event

examples/manifests/configmap.yaml, go.mod, go.sum, plugins/ptp_operator/metrics/metrics.go
=> Modified maxoffset and holdover 

Dockerfile
Change base image to UBI:minimal
=> Change base image to UBI:minimal

README.md
=> Added description in read me

OWNERS, OWNERS_ALIASES
=> Add owners

plugins/ptp_operator/ptp_operator_plugin.go
This PR is minor to change socket director from /tmp/metrics.sock to /cloud-native/events.sock
=> Added meaningful name to socket dir

go.mod, go.sum, vendor/modules.txt
update local dependencies to use appropriate releases:
SDK-GO release/v.0.1.0
REST API => release/v.0.1.0
signed-off-by=nparekh@redhat.com
=> Create release 4.9 branch and manage local dependencies

go.mod, go.sum, plugins/hw_event/hw_event_plugin.go, vendor/github.com/cloudevents/sdk-go/protocol/amqp/v2/go.mod, vendor/github.com/cloudevents/sdk-go/protocol/amqp/v2/go.sum, vendor/github.com/google/uuid/null.go, vendor/github.com/google/uuid/uuid.go, vendor/github.com/google/uuid/version4.go, vendor/github.com/redhat-cne/sdk-go/pkg/channel/data.go, vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go, vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event.go, vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event_ce.go, vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event_data.go, vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event_marshal.go, vendor/github.com/redhat-cne/sdk-go/pkg/hwevent/event_unmarshal.go, vendor/github.com/redhat-cne/sdk-go/pkg/localmetrics/localmetrics.go, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go, vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go, vendor/modules.txt
This update works with the Redfish schema updates in sdk-go repo.
A successful build is depending on sdk-go repo being updated first.
=> Integrate with Redfish schema

OWNERS
Update Bugzilla Component details in OWNERS file
Signed-off-by: nishant-parekh <nparekh@redhat.com>
=> Update Bugzilla Component details in OWNERS file

plugins/ptp_operator/metrics/metrics.go
When summary_interval is set to anything other than -4 , the log  behaves differently.
//ptp4l.0.config master offset   -2162130 s2 freq +22451884  delay 374976
//ptp4l.0.config eno1 sys offset        -5 s2 freq   +6024 delay    467
//ptp4l.0.config CLOCK_REALTIME  phc offset        -5 s2 freq   +6024 delay    467
So to handle the parsing offset in such conditions, knowing that the offset  field is expected to be available as field 2 , if it is not found  at that position then log an error and return.
Also replace phc and sys(known values) to empty make the offset log to generic format with interface at position 1 and offset at position 2 
//ptp4l.0.config {INTERFACE}  offset   -2162130 s2 freq +22451884  delay 374976
=> Bug 1999185: Fixed offset parsing error

README.md
=> Readme changes for check codefreeze sync

README.md
=> Update endpoint for cloud-event-proxy

plugins/ptp_operator/config/config.go
Previous  fix introduced a nil pointer exception. This PR will fix that
=> Bug 2004721: Fixed ptp threshold updates not updating values for CLOCK_REALTIME

plugins/ptp_operator/config/config.go
Last PR to fix ptp threshold updates not updating values for CLOCK_REALTIME
introduced nil pointer exception. This PR fixes that .
This PR is for 4.9
=> Bug 2004137: fixed nil error and ptp threshold updates not updating values for CLOCK_REALTIME 

plugins/ptp_operator/config/config.go, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/ptp_operator_plugin.go
This PR ,
fixes minor bugs and adds event notification for master interface.
Fixed channel close bug , missing  metrics updated and  generate event for master interface(dual master interface are considered as on, will be fixed in future changes)
=> BUG 2007379: Added event for master interface

plugins/ptp_operator/ptp_operator_plugin.go
=> Fixed metrics name typo

plugins/ptp_operator/ptp_operator_plugin.go
Get PTP_STATUS was not picking up mster interface and renmaing it to slave interface masked with 'X' for index
/cluster/cnfde7.ptp.lab.eng.bos.redhat.com/ptp/interface/ens5fx/master
=> Fixed  get status not picking proper master interface

go.mod, go.sum, vendor/modules.txt
=> update sdk-go and rest-api to go 1.17

Dockerfile.local, cmd/main_test.go, examples/consumer/main.go, examples/manifests/consumer.yaml, examples/manifests/qpid-dispatcher/config.yaml, examples/manifests/qpid-dispatcher/qpid-dispatcher.yaml, hack/common/cne.sh, hack/common/common.sh, hack/common/consumer.sh, hack/common/router.sh, hack/deploy_test.sh, hack/run-functests.sh, pkg/plugins/handler_test.go, plugins/mock/mock_plugin.go, plugins/ptp_operator/ptp_operator_plugin_test.go, test/cne/cne.go, test/cne/test_suite_test.go, test/utils/consts.go, test/utils/nodes/nodes.go
Added integration test for validating producer and consumer event
=> e2e test for verifying producer ,consumer and router

go.mod, go.sum, vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/event_marshal.go, vendor/modules.txt
=> Update sdk-go modules for Redfish compliance update

Dockerfile.dev, examples/consumer.Dockerfile.dev
=> Add Dockerfile.dev for quay.io build triggers

docs/development.md, examples/consumer/main.go, hack/common/cne.sh, hack/common/common.sh, hack/common/consumer.sh, hack/deploy_test.sh, plugins/mock/mock_plugin.go, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/ptp_operator_plugin.go, plugins/ptp_operator/ptp_operator_plugin_test.go, plugins/ptp_operator/socket/socket_test.go, plugins/ptp_operator/types/types.go
Reverts redhat-cne/cloud-event-proxy#95
=> Revert "CNF-4018 Enable Flexible Registration for Multiple PTP Events clock-class-change,status and os-sync"

examples/consumer/main.go, go.mod, go.sum, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/ptp_operator_plugin.go, vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go, vendor/github.com/redhat-cne/sdk-go/v1/event/event.go, vendor/modules.txt
Fixes lost event source
Also minor fix on  ping status call returning 404 error
plus nil pointer exception when PTP starts with the faulty interface.
=> Bug 2067312: PPT event source is lost when received by the consumer

go.mod, go.sum, plugins/ptp_operator/metrics/metrics.go, vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go, vendor/github.com/redhat-cne/sdk-go/v1/event/event.go, vendor/modules.txt
Fixes lost event source
plus nil pointer exception when PTP starts with the faulty interface.
=> Bug 2067311: PTP event source is lost when received by the consumer 

plugins/ptp_operator/metrics/logparser.go, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/metrics/registry.go
linux ptpdaemon will be logging no of times ptp4l/phc2sys process dies and restarts.
The event framewortk will parse the logs for these messages and generate metrics
to capture process restart count and current status of the ptp4l/phc2sys process
Also send events when ptp4l/phc2sys is down, notificying subscribers on status of the ptp clock.
=> Generate ptp4l/phc2sys process status metrics and events

go.mod, go.sum, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go, vendor/modules.txt
prometheus/client_golang: Denial of service using InstrumentHandlerCounter
updated promeeus go-client to 1.11.1
=> Bug 2067737: Denial of service using InstrumentHandlerCounter

README.md, plugins/README.md
documentation to explain how ptp plugin works are added to readme under plugin folder
=> Bug 2090774: Add Readme to plugin folder

plugins/ptp_operator/metrics/metrics.go
Fix clock realtime to be in FREERUN state only
=> BUG 2109518: Phc2sys should not be in HOLDOVER

cmd/main.go, examples/consumer/main.go, examples/manifests/kustomization.yaml, go.mod, go.sum, pkg/common/common.go, plugins/http/http_plugin.go, plugins/ptp_operator/metrics/manager.go, plugins/ptp_operator/ptp_operator_plugin.go, test/cne/cne.go, vendor/github.com/redhat-cne/sdk-go/pkg/channel/data.go, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go, vendor/github.com/redhat-cne/sdk-go/pkg/subscriber/subscriber.go, vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go, vendor/github.com/redhat-cne/sdk-go/v1/http/http.go, vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go, vendor/modules.txt
ping status fires events for all subscribers, the fix will isolate only the called client
=> Fix pingStatus

plugins/ptp_operator/metrics/manager.go
=> typo fix on building source of the event

Dockerfile.dev
=> update base image in Dockerfile.dev

examples/consumer.Dockerfile, examples/consumer/main.go, examples/manifests/consumer.yaml, go.mod, go.sum, pkg/common/common.go, plugins/ptp_operator/ptp_operator_plugin.go, vendor/github.com/redhat-cne/rest-api/routes.go, vendor/github.com/redhat-cne/rest-api/server.go, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go, vendor/github.com/redhat-cne/sdk-go/v1/pubsub/pubsub.go, vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go, vendor/modules.txt
Event Pull Status Notification GET Method not working as per o-Ran spec
=> Amq current state API call fix 

.golangci.yaml, plugins/ptp_operator/config/config.go, plugins/ptp_operator/metrics/ptp4lParse.go, plugins/ptp_operator/ptp4lconf/ptp4lConfig.go, plugins/ptp_operator/ptp_operator_plugin.go, plugins/ptp_operator/socket/socket.go, test/utils/client/clients.go, test/utils/nodes/nodes.go
=> Fix golint and typo

Makefile, cmd/main.go, examples/consumer/main.go, examples/manifests/consumer.yaml, go.mod, go.sum, hack/common/cne.sh, hack/common/common.sh, hack/common/consumer.sh, hack/deploy_test.sh, plugins/mock/mock_plugin.go, plugins/ptp_operator/ptp_operator_plugin.go, test/cne/cne.go, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go, vendor/modules.txt
Added e2e for HTTP 
for HTTP testing 
./hack/deploy_test.sh deploy HTTP
make functests
For AMQ testing
./hack/deploy_test.sh 
make functests
=> Update e2e to support both HTTP and AMQ

go.mod, go.sum, vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go, vendor/modules.txt
=> 4.10 Fix amq router race condition: update vendors only

go.mod, go.sum, vendor/modules.txt
=> update rest-api version

go.mod, go.sum, vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go, vendor/modules.txt
=> 4.11 Fix amq router race condition: update vendors only

go.mod, go.sum, vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go, vendor/modules.txt
=> Bug OCPBUGS-3350: Fix amq router race condition: update vendor only

go.mod, go.sum, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go, vendor/modules.txt
=> Bug OCPBUGS-4961: Update vendor files for amqp resource leak fix

go.mod, go.sum, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go, vendor/modules.txt
=> [release-4.12] Bug OCPBUGS-4255: Update vendor files for amqp resource leak fix

.golangci.yaml, Makefile, cmd/main.go, examples/producer/main.go, hack/gofmt.sh, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/metrics/ptp4lParse.go, plugins/ptp_operator/stats/stats.go
=> OCPBUGS-5290: [release-4.11] Fix CLOCK_REALTIME going to HOLDOVER in metrics

go.mod, go.sum, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go, vendor/modules.txt
=> [release-4.11] Bug OCPBUGS-4964: Update vendor files for amqp resource leak fix

go.mod, go.sum, vendor/github.com/redhat-cne/sdk-go/v1/amqp/amqp.go, vendor/modules.txt
=> update sdk-go model for increasing amq timeout

plugins/ptp_operator/ptp_operator_plugin.go
=> Bug OCPBUGS-5293: Dual Nic with single phc2sys throws nil pointer exception.

plugins/ptp_operator/metrics/manager.go, plugins/ptp_operator/metrics/ptp4lParse.go
fix interface going on FREERUN immediate to holdover
=> BUG OCPBUGS-5377: Fix channel staying in close state

plugins/ptp_operator/metrics/ptp4lParse.go
=> Remove duplicate logs when slave interface down

plugins/ptp_operator/metrics/logparser.go, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/metrics/ptp4lParse.go
Add events  for GM with ts2phc
=> Add metrics and events for ts2phc

plugins/ptp_operator/ptp_operator_plugin.go
=> OCPBUGS-5357: [release-4.11] Dual Nic with single phc2sys throws nil pointer exception. n sending events

go.mod, go.sum, vendor/modules.txt
=> update sdk-go, rest-api versions for amq timeout

cmd/main.go, examples/consumer/deployment/deployment.yaml, plugins/ptp_operator/metrics/logparser.go, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/metrics/ptp4lParse.go
=> fix ts2phc events and metrics

README.md, cmd/main.go, cmd/main_test.go, examples/consumer/deployment/deployment.yaml, examples/consumer/main.go, examples/manifests/consumer.yaml, examples/producer/main.go, hack/common/consumer.sh, plugins/README.md, test/cne/cne.go
Adds the o in front of cloudNotifications
OCPBUGS-7441
=> BUG OCPBUGS-7441: Match the O-RAN specification for the ocloudNotifications URI

README.md
=> doc update: configure persistent storage for event producer

Makefile, go.mod, go.sum, plugins/README.md, plugins/ptp_operator/metrics/logparser.go, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/metrics/ptp4lParse.go, plugins/ptp_operator/types/types.go, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go, vendor/modules.txt
events were not sent out during this transition
add  3 more states 
SLAVE to MASTER"
SLAVE to GRAND_MASTER
SLAVE to LISTENING
moves to HOLDOVER state
=> BUG OCPBUGS-5465: Fix SLAVE port going to master or listening state

plugins/ptp_operator/metrics/registry.go, plugins/ptp_operator/types/types.go
fix listening string in metrics
=> patch LISTENING string

cmd/main.go, docs/metrics.md, examples/manifests/consumer.yaml, go.mod, go.sum, plugins/README.md, plugins/ptp_operator/config/config.go, vendor/github.com/redhat-cne/rest-api/routes.go, vendor/github.com/redhat-cne/sdk-go/pkg/channel/data.go, vendor/github.com/redhat-cne/sdk-go/pkg/localmetrics/localmetrics.go, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/amqp/amqp.go, vendor/github.com/redhat-cne/sdk-go/pkg/protocol/http/http.go, vendor/github.com/redhat-cne/sdk-go/pkg/store/store.go, vendor/github.com/redhat-cne/sdk-go/pkg/store/subscriber/subscriber.go, vendor/github.com/redhat-cne/sdk-go/pkg/subscriber/subscriber.go, vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go, vendor/modules.txt
Fix delete subscription on client dead
=> OCPBUGS-8003: Fix lost client subscription clean up and add validation 

examples/consumer/main.go, examples/simplehttp/common/currentstate.go, examples/simplehttp/common/httpclient.go, examples/simplehttp/common/subscribe.go, examples/simplehttp/external-service.yaml, examples/simplehttp/main.go
Shows examples of how to HTTP protocol directly with the producer.
This is not tested or supported yet
=> Add example to use event subscription without using side car

cmd/main.go, plugins/ptp_operator/metrics/manager.go, plugins/ptp_operator/metrics/registry.go, plugins/ptp_operator/ptp_operator_plugin.go
Backported changes to fix process metrics on edit of ptpconfig
=> [release-4.12] OCPBUGS-12361: PTP metrics - Unexpected metrics for old phc2sys appears in metrics after modify ptpconfigs

plugins/ptp_operator/event/event.go
fix crash loop due to nil pointer
=> OCPBUGS-17322: linuxptp-daemon pod status changes to Error and CrashLoopBackOff after a ptpconfig is loaded

plugins/ptp_operator/event/event.go, plugins/ptp_operator/metrics/logparser.go, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/stats/stats.go
Fix registering existing metrics on restart
=> OCPBUGS-17945: cloud Event Proxy error in log after editing ptp config

plugins/ptp_operator/metrics/logparser.go, plugins/ptp_operator/metrics/manager.go, plugins/ptp_operator/metrics/metrics_test.go, plugins/ptp_operator/metrics/registry.go
- Added events verification
- Added more tests
- Refactor
=> Refactor and improve coverage on metrics unit tests

examples/simplehttp/common/subscribe.go, examples/simplehttp/external-service.yaml, examples/simplehttp/main.go, plugins/ptp_operator/metrics/logparser.go, plugins/ptp_operator/metrics/manager.go, plugins/ptp_operator/metrics/metrics.go, plugins/ptp_operator/ptp_operator_plugin.go, plugins/ptp_operator/stats/stats.go
GetCurrentState of PTP for GM should return GNSS state events if consumer subscribed to it .
=> OCPBUGS-25430: PTP event getCurrentState for GNSS return event not found

.snyk
=> add .snyk file for low and medium level CWEs

examples/consumer/main.go
Log decoded received event string.
=> Log decoded received event

plugins/ptp_operator/metrics/metrics.go
This is due to ts2phc reporting high offset. But clock state for ts2phc was showing as locked.
This PR  tries to update metrics accurately when ts2phc is high .
=> OCPBUGS-36496: GM clock_state stuck in freerun

cmd/main.go, examples/consumer/main.go, examples/producer/main.go, examples/simplehttp/common/subscribe.go, go.mod, go.sum, pkg/common/common.go, pkg/storage/kubernetes/client.go, plugins/ptp_operator/metrics/manager.go, vendor/github.com/redhat-cne/rest-api/v2/routes.go, vendor/github.com/redhat-cne/rest-api/v2/server.go, vendor/github.com/redhat-cne/sdk-go/pkg/common/common.go, vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go, vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go, vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/resource.go, vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/syncstate.go, vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/types.go, vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go, vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_unmarshal.go, vendor/github.com/redhat-cne/sdk-go/pkg/subscriber/subscriber.go, vendor/github.com/redhat-cne/sdk-go/pkg/subscriber/subscriber_writer.go, vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go, vendor/modules.txt
- add SubscriberAPI to SCConfiguration so that configMap can be restored.
- Remove local store for pubsub: sub.json. Now access to sub info only through SubscriberAPI/store.
- Update UriLocation to use service name.
More details in doc https://docs.google.com/document/d/1aIgGWhFDDz9aI7mIZm_nlkb99UrV7hv5gS5m_XShCt4/edit
=> CNF-13067: O-RAN V3 Rest Api: Status Notification

go.mod, go.sum, plugins/ptp_operator/metrics/manager.go, plugins/ptp_operator/ptp_operator_plugin.go, vendor/github.com/redhat-cne/rest-api/v2/routes.go, vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go, vendor/modules.txt
trigger overall sync-state event when either ptp-state-change or os-clock-sync-state-change events are triggered.
=> OCPBUGS-33594: trigger overall sync-state events

plugins/ptp_operator/metrics/logparser.go, plugins/ptp_operator/metrics/registry.go
Add metrics help text for DUS and DNU 
Fix the Clock quality value to show sum of QL+ EXtQL
=> fix metrics help and value for synce

cmd/main.go, hack/common/cne.sh
- Exit on attempt to run APIv1.
- Remove deprecated code.
=> Update main.go to drop support for API v1

test/cne/cne.go, test/utils/pods/pods.go
Add timeouts on waiting for deployment and pods.
=> Fix e2e test checking for pods

plugins/ptp_operator/metrics/logparser.go
Adding some missing transitions to LISTENING for the DualFollower mode
=> Add missing transitions to FOLLOWING

plugins/ptp_operator/metrics/manager.go, plugins/ptp_operator/metrics/manager_test.go
This pull request addresses issues related to concurrent map writes and read/write lock handling in the PTPEventManager class. The changes ensure proper synchronization when accessing and modifying the Stats map to prevent race conditions and potential panics.
Changes
Initialization of Stats Map:
Ensured that the Stats map is properly initialized in the NewPTPEventManager constructor to avoid "assignment to entry in nil map" panic.
**Synchronization in GetStats Method:** 
Updated the GetStats method to use a read lock (RLock) for reading and a write lock (Lock) for modifying the Stats map. This prevents concurrent write issues.
**Synchronization in GetStatsForInterface Method:**
Corrected the GetStatsForInterface method to use a read lock for reading and a write lock for modifying the …
=> OCPBUGS-54160: Handle concurrent map read and write for stats object

Makefile, cmd/main.go
Add the commit hash that to cloud-event-proxy log at build time
=> Add commit log at build time

plugins/ptp_operator/ptp_operator_plugin.go
refactor to pass lint in 4.17 and earlier releases
=> fix lint for older releases

plugins/ptp_operator/metrics/manager.go, plugins/ptp_operator/metrics/manager_test.go
This is an manual cherry-pick of https://github.com/redhat-cne/cloud-event-proxy/pull/445
=> [release-4.17] OCPBUGS-54964: handle concurrent map read and write for stats object

examples/consumer/main.go, pkg/common/common.go, pkg/storage/kubernetes/client_test.go
also added some refactor changes from https://github.com/redhat-cne/cloud-event-proxy/pull/485 review comments
=> Update k8s client test to v2

Makefile, cmd/main.go, examples/consumer/main.go, examples/manifests/consumer.yaml, pkg/common/common.go, pkg/restclient/client.go, pkg/storage/kubernetes/client.go, pkg/storage/kubernetes/client_test.go, plugins/ptp_operator/config/config.go
This is a manual cherry-pick of https://github.com/redhat-cne/cloud-event-proxy/pull/510
- Add commit log at build time
- add git commit ID in consumer image
- add error handling in configmap and consumer app subscription
=> [release-4.15] add error handling in configmap and consumer app subscription

Makefile, cmd/main.go, examples/consumer/main.go, examples/manifests/consumer.yaml, pkg/common/common.go, pkg/restclient/client.go, pkg/storage/kubernetes/client.go, pkg/storage/kubernetes/client_test.go, plugins/ptp_operator/config/config.go
This is a manual cherry-pick of https://github.com/redhat-cne/cloud-event-proxy/pull/517
Add commit log at build time
add git commit ID in consumer image
add error handling in configmap and consumer app subscription
=> [release-4.14] OCPBUGS-56548: add error handling in configmap and consumer app subscription

plugins/ptp_operator/metrics/registry.go
Update clock class help message to include boundary clock holdover classes
/cc @aneeshkp @josephdrichard @nocturnalastro @jzding
=> OCPBUGS-60594: Update clock class help message

cmd/main_test.go, plugins/ptp_operator/metrics/logparser_test.go, plugins/ptp_operator/metrics/manager.go, plugins/ptp_operator/metrics/manager_test.go
Use the aggregated node state from GetNodeSyncState for both comparison and emission of event.sync.sync-status.synchronization-state-change. This prevents multiple  events for different profiles 
files 
plugins/ptp_operator/metrics/manager.go
plugins/ptp_operator/metrics/manager_test.go
Tests:
Added TestPublishEvent_UsesAggregatedNodeStateAndDedupes.
=>  OCPBUGS-58326: update syncstate to use overall state of the node  
